#  Importing Libraries

In [76]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [77]:
tf.__version__

'2.12.0'

# Data Pre-processing

## Importing Data Set

In [78]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

In [79]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [80]:
print(Y)

[1 0 1 ... 1 1 0]


## Encoding Categorical Data

In [81]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [82]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [83]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [84]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [85]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [86]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [87]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building ANN

In [88]:
ann = tf.keras.models.Sequential()

In [89]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [90]:
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))

In [91]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [92]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [93]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [94]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [95]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [96]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

In [97]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [98]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6699 - accuracy: 0.7300
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6098 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5700 - accuracy: 0.8010
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5269 - accuracy: 0.8188
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5008 - accuracy: 0.8219
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4856 - accuracy: 0.8216
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4753 - accuracy: 0.8227
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4689 - accuracy: 0.8238
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4644 - accuracy: 0.8249
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4621 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3207 - accuracy: 0.8702
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3204 - accuracy: 0.8704
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3196 - accuracy: 0.8699
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3201 - accuracy: 0.8694
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3198 - accuracy: 0.8706
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3212 - accuracy: 0.8691
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3192 - accuracy: 0.8691
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3189 - accuracy: 0.8685
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3201 - accuracy: 0.8698
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3186 - accuracy: 

In [99]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 118ms/step
[[ True]]


In [100]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [1 0]
 [0 0]
 [0 0]]


In [101]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1504   91]
 [ 202  203]]


0.8535